version: '3'
services:
  php8:
    build:
      context: docker/php8
    working_dir: /var/www
    volumes:
      - ./:/var/www
    container_name: "pingback_php8"

  php7:
    build:
      context: docker/php7
    working_dir: /var/www
    volumes:
      - ./:/var/www
    container_name: "pingback_php7"
